## DATABASE PROPERTIES
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/choice
    username: postgres
    password: password
  jpa:
    database: postgresql
    hibernate.ddl-auto: create
    show-sql: false

# Default port used by frontend
server:
  port: 9090
  context-path: /api/v1
