## DATABASE PROPERTIES
spring:
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:a5l
    username: sa
    password:
  jpa:
    database: HSQL
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: false
    properties.hibernate.default_schema: PUBLIC

  thymeleaf:
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html

server:
  port: 8080
  context-path: /choice

wisvch:
  connect:
    issuerUri: https://connect.ch.tudelft.nl/
    clientUri: http://localhost:8080/choice
    admin-groups: dienst2, chbeheer
